language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile test
scala:
   - 2.11.4
before_script:
  - mkdir $TRAVIS_BUILD_DIR/tmp
  - export SBT_OPTS="-Djava.io.tmpdir=$TRAVIS_BUILD_DIR/tmp"
